### ISSUE TITLE
rewrite

### ISSUE THREAD

**Issue by dfltbox** [CampusRoute/CampusRoute#7]
**Is your feature request related to a problem? Please describe.**
stop using react

**Describe the solution you'd like**
please use svelte or vue

**Describe alternatives you've considered**
none

**Additional context**
do it

**Comment by luuunnaah** [comment]
or use ts

**Comment by dfltbox** [comment]
this too

**Comment by dfltbox** [comment]
WTF

**Comment by luuunnaah** [comment]
abuse

**Comment by luuunnaah** [comment]
let's start a convo in issues

**Comment by ararouv2** [comment]
sex

**Comment by jackwellerreal** [comment]
We have no plans to change the framework used for Campus Route. We might use Typescript but we will worry about changing language once Campus Route is finished.
